#!/usr/bin/python3

import json
from sender import Sender
from reader import Reader

import time
import logging

PORT = '/dev/ttyUSB0'
BAUD = 9600

reader = Reader(port=PORT, baud=BAUD)
sender = Sender(port=PORT, baud=BAUD)
counter = int(0)

while(1):
    presence = json.loads(reader.getData())['presence']

    if(presence == True & counter < 2):
        sender.alimentar()
        logging.info('PET ALIMENTADO.\n')
        counter + 1

    if(counter == 2):
        counter = int(0)
        time.sleep(3600)
        
